language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild SoundCloud.API.Client.sln
  - nunit-console SoundCloud.API.Client.Test/bin/Debug/SoundCloud.API.Client.Test.dll
